#!/bin/sh

# Use pgrep to check if the process is running
if pgrep -f "messaging:subscribe" > /dev/null
then
    exit 0
else
    echo "❌ Healthcheck failed: Messaging subscriber process cannot be found."
    exit 1
fi